[tool.poetry]
name = "fake-standup"
version = "0.1.0"
description = ""
authors = ["Ryan Downing <ryansdowning1@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
numpy = "^1.22.3"
opencv-python = "^4.5.5"
ipykernel = "^6.12.1"
pyvirtualcam = "^0.9.1"
pygame = "^2.1.2"
ffmpeg = "^1.4"
moviepy = "^1.0.3"

[tool.poetry.dev-dependencies]
black = "^22.3.0"
pre-commit = "^2.18.1"
isort = "^5.10.1"
pylint = "^2.13.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
